name: Deploy

on:
  push:
    branches:
      - staging
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build

      - name: fr fallback homepage
        run: "cp _site/fr/index.html _site/index.html"

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/staging'
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./_site
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_dir: staging

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./_site
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_dir: .